# MobArena v0.96.9 - Config-file
# Read the Wiki for details on how to set up this file: http://goo.gl/F5TTc
# Note: You -must- use spaces instead of tabs!
global-settings:
  enabled: true
  allowed-commands: /list, /pl
  update-notification: true
classes:
  Tank:
    items: iron_sword, potion:8229:2
    armor: 310,311,312,313
  Chemist:
    items: stone_sword, potion:16428:30, potion:16388:8, potion:16389:20, potion:8197:3, potion:8226:1
    armor: 314,315,316,317
  Oddjob:
    items: stone_sword, flint_and_steel, netherrack:2, tnt:4, potion:8197:3
    armor: 298,299,300,301
  Medic:
    items: diamond_helmet 0:3;34:3, gold_chestplate 0:3;34:3, gold_leggings 0:3;34:3, gold_boots 0:3;34:3, gold_sword 34:3;16:4, potion:16421:1, potion:16421:1, potion:16421:1, potion:16421:1, potion:16421:1, potion:16421:1, potion:8258:1, golden_apple:6
    armor: ''
  Knight:
    items: leather_helmet 0:1;34:1, leather_chestplate 0:1;34:1, leather_leggings 0:1;34:1, leather_boots 0:1;34:1, iron_sword 34:1;16:1, potion:16421:1, potion:16421:1, potion:16421:1, golden_apple:4
    armor: ''
  Archer:
    items: iron_helmet 0:2, leather_chestplate 0:2, leather_leggings 0:2, leather_boots 0:2, stone_sword 34:3;19:1, bow 51:1;34:3;49:1;48:1, potion:16418:1, potion:16418:1, golden_apple:6, arrow
    armor: ''
  Brute:
    items: iron_helmet 34:1, diamond_chestplate 34:1, diamond_leggings 34:1, diamond_boots 34:1, iron_sword 16:1;18:1, potion:16425:1, potion:16425:1, potion:16425:1, golden_apple:2
    armor: ''
  Pyromancer:
    items: chainmail_helmet 34:3;0:2;1:4, chainmail_chestplate 34:3;0:2;1:4, chainmail_leggings 34:3;0:2;1:4, chainmail_boots 34:3;0:2;1:4, iron_sword 16:1;20:2, potion:16451:1, potion:16451:1, potion:16451:1, golden_apple:4
    armor: ''
  Knockback:
    items: iron_helmet 0:1;34:2, iron_chestplate 0:1;34:2, iron_leggings 0:1;34:2, iron_boots 0:1;34:2, diamond_sword 19:2, bow 34:1;49:2, potion:16458:1, potion:16458:1, golden_apple:6, arrow:32
    armor: ''
arenas:
  default:
    settings:
      world: world
      enabled: true
      protect: true
      entry-fee: ''
      clear-wave-before-next: false
      clear-boss-before-next: false
      clear-wave-before-boss: false
      soft-restore: false
      soft-restore-drops: false
      require-empty-inv-join: false
      require-empty-inv-spec: false
      hellhounds: false
      pvp-enabled: false
      monster-infight: false
      allow-teleporting: false
      spectate-on-death: true
      auto-respawn: true
      share-items-in-arena: true
      min-players: 0
      max-players: 0
      max-join-distance: 0
      first-wave-delay: 5
      wave-interval: 15
      final-wave: 0
      monster-limit: 100
      monster-exp: false
      keep-exp: true
      food-regen: false
      lock-food-level: true
      player-time-in-arena: world
      auto-ignite-tnt: false
      auto-start-timer: 0
      start-delay-timer: 0
      auto-ready: false
      use-class-chests: false
      display-waves-as-level: false
      display-timer-as-level: false
      use-scoreboards: true
      isolated-chat: false
      global-join-announce: false
      global-end-announce: false
      show-death-messages: true
    waves:
      recurrent:
        def1:
          type: default
          priority: 1
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            wolves: 10
        spec1:
          type: special
          priority: 2
          frequency: 4
          monsters:
            powered-creepers: 10
            zombie-pigmen: 10
            angry-wolves: 10
            blazes: 10
      single:
        swarm1:
          type: swarm
          wave: 6
          monster: slime
          amount: low
        boss1:
          type: boss
          wave: 10
          monster: cave_spider
          health: high
          abilities: arrows, root-target, throw-nearby
    rewards:
      waves:
        every:
          '3': feather, bone, stick
          '5': dirt:4, gravel:4, stone:4
          '10': iron_ingot:10, gold_ingot:8
        after:
          '7': minecart, storage_minecart, powered_minecart
          '13': iron_sword, iron_pickaxe, iron_spade
          '16': diamond_sword
    coords:
      spawnpoints: {}
      containers: {}
    class-limits:
      Archer: -1
      Oddjob: -1
      Chemist: -1
      Tank: -1
      Knight: -1
  DesertArena:
    settings:
      world: minigames
      enabled: true
      protect: true
      entry-fee: ''
      clear-wave-before-next: false
      clear-boss-before-next: false
      clear-wave-before-boss: false
      soft-restore: false
      soft-restore-drops: false
      require-empty-inv-join: false
      require-empty-inv-spec: false
      hellhounds: false
      pvp-enabled: false
      monster-infight: false
      allow-teleporting: false
      spectate-on-death: true
      auto-respawn: true
      share-items-in-arena: true
      min-players: 0
      max-players: 0
      max-join-distance: 0
      first-wave-delay: 5
      wave-interval: 15
      final-wave: 0
      monster-limit: 100
      monster-exp: false
      keep-exp: true
      food-regen: false
      lock-food-level: true
      player-time-in-arena: world
      auto-ignite-tnt: false
      auto-start-timer: 0
      start-delay-timer: 0
      auto-ready: false
      use-class-chests: false
      display-waves-as-level: false
      display-timer-as-level: false
      use-scoreboards: true
      isolated-chat: false
      global-join-announce: false
      global-end-announce: false
      show-death-messages: true
    waves:
      recurrent:
        def1:
          type: default
          priority: 1
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            wolves: 10
        spec1:
          type: special
          priority: 2
          frequency: 4
          monsters:
            powered-creepers: 10
            zombie-pigmen: 10
            angry-wolves: 10
            blazes: 10
      single:
        swarm1:
          type: swarm
          wave: 6
          monster: slime
          amount: low
        boss1:
          type: boss
          wave: 10
          monster: cave_spider
          health: high
          abilities: arrows, root-target, throw-nearby
    rewards:
      waves:
        every:
          '3': feather, bone, stick
          '5': dirt:4, gravel:4, stone:4
          '10': iron_ingot:10, gold_ingot:8
        after:
          '7': minecart, storage_minecart, powered_minecart
          '13': iron_sword, iron_pickaxe, iron_spade
          '16': diamond_sword
    coords:
      spawnpoints:
        81,5,-74: 81.5,5,-73.5,0.0,0.0,minigames
        99,5,-56: 99.5,5,-55.5,0.0,0.0,minigames
        117,5,-74: 117.5,5,-73.5,0.0,0.0,minigames
        99,5,-92: 99.5,5,-91.5,0.0,0.0,minigames
        90,5,-83: 90.5,5,-82.5,0.0,0.0,minigames
        90,5,-65: 90.5,5,-64.5,0.0,0.0,minigames
        108,5,-65: 108.5,5,-64.5,0.0,0.0,minigames
        108,5,-83: 108.5,5,-82.5,0.0,0.0,minigames
        110,7,-74: 110.5,7,-73.5,0.0,0.0,minigames
        88,7,-74: 88.5,7,-73.5,0.0,0.0,minigames
        99,7,-85: 99.5,7,-84.5,0.0,0.0,minigames
        99,7,-63: 99.5,7,-62.5,0.0,0.0,minigames
      containers:
        103,12,-72: 103,12,-72,0.0,0.0,minigames
        99,3,-83: 99,3,-83,0.0,0.0,minigames
        93,6,-69: 93,6,-69,0.0,0.0,minigames
      p2: 119,17,-54,0.0,0.0,minigames
      p1: 79,3,-94,0.0,0.0,minigames
      l1: 96,3,-45,0.0,0.0,minigames
      l2: 112,9,-26,0.0,0.0,minigames
      lobby: 104.5,5,-30.5,-174.98,0.0,minigames
      arena: 99.5,8,-73.5,254.77,0.0,minigames
      spectator: 99.5,8,-73.5,150.82,0.0,minigames
    class-limits:
      Archer: -1
      Oddjob: -1
      Chemist: -1
      Tank: -1
      Knight: -1
  Desert:
    settings:
      world: minigames
      enabled: true
      protect: true
      entry-fee: ''
      clear-wave-before-next: false
      clear-boss-before-next: false
      clear-wave-before-boss: false
      soft-restore: false
      soft-restore-drops: false
      require-empty-inv-join: false
      require-empty-inv-spec: false
      hellhounds: false
      pvp-enabled: false
      monster-infight: false
      allow-teleporting: false
      spectate-on-death: true
      auto-respawn: true
      share-items-in-arena: true
      min-players: 1
      max-players: 6
      max-join-distance: 0
      first-wave-delay: 15
      wave-interval: 15
      final-wave: 30
      monster-limit: 23
      monster-exp: true
      keep-exp: true
      food-regen: true
      lock-food-level: true
      player-time-in-arena: world
      auto-ignite-tnt: false
      auto-start-timer: 0
      start-delay-timer: 0
      auto-ready: false
      use-class-chests: false
      display-waves-as-level: false
      display-timer-as-level: false
      use-scoreboards: true
      isolated-chat: false
      global-join-announce: true
      global-end-announce: true
      show-death-messages: true
    waves:
      recurrent:
        def1:
          type: default
          priority: 1
          frequency: 1
          monsters:
            zombies: 10
            skeletons: 10
            spiders: 10
            creepers: 10
            wolves: 10
        spec1:
          type: special
          priority: 2
          frequency: 4
          monsters:
            powered-creepers: 10
            zombie-pigmen: 10
            angry-wolves: 10
            blazes: 10
      single:
        swarm1:
          type: swarm
          wave: 6
          monster: slime
          amount: low
        boss1:
          type: boss
          wave: 10
          monster: cave_spider
          health: high
          abilities: arrows, root-target, throw-nearby
    rewards:
      waves:
        every:
          '3': feather, bone, stick
          '5': dirt:4, gravel:4, stone:4
          '10': iron_ingot:10, gold_ingot:8
        after:
          '7': minecart, storage_minecart, powered_minecart
          '13': iron_sword, iron_pickaxe, iron_spade
          '16': diamond_sword
    coords:
      spawnpoints:
        297,6,-60: 297.5,6,-59.5,0.0,0.0,minigames
        296,6,-60: 296.5,6,-59.5,0.0,0.0,minigames
        296,6,-61: 296.5,6,-60.5,0.0,0.0,minigames
        296,6,-66: 296.5,6,-65.5,0.0,0.0,minigames
        296,6,-67: 296.5,6,-66.5,0.0,0.0,minigames
        297,6,-66: 297.5,6,-65.5,0.0,0.0,minigames
        291,6,-52: 291.5,6,-51.5,0.0,0.0,minigames
        291,6,-51: 291.5,6,-50.5,0.0,0.0,minigames
        290,6,-51: 290.5,6,-50.5,0.0,0.0,minigames
        290,6,-50: 290.5,6,-49.5,0.0,0.0,minigames
        294,8,-32: 294.5,8,-31.5,0.0,0.0,minigames
        295,8,-32: 295.5,8,-31.5,0.0,0.0,minigames
        308,5,-48: 308.5,5,-47.5,0.0,0.0,minigames
        308,5,-53: 308.5,5,-52.5,0.0,0.0,minigames
        303,5,-53: 303.5,5,-52.5,0.0,0.0,minigames
        303,5,-48: 303.5,5,-47.5,0.0,0.0,minigames
        322,5,-34: 322.5,5,-33.5,0.0,0.0,minigames
        321,5,-34: 321.5,5,-33.5,0.0,0.0,minigames
        322,5,-35: 322.5,5,-34.5,0.0,0.0,minigames
        320,4,-60: 320.5,4,-59.5,0.0,0.0,minigames
        320,4,-61: 320.5,4,-60.5,0.0,0.0,minigames
        320,4,-59: 320.5,4,-58.5,0.0,0.0,minigames
        321,4,-60: 321.5,4,-59.5,0.0,0.0,minigames
        321,4,-59: 321.5,4,-58.5,0.0,0.0,minigames
        321,4,-61: 321.5,4,-60.5,0.0,0.0,minigames
        322,4,-61: 322.5,4,-60.5,0.0,0.0,minigames
        322,4,-60: 322.5,4,-59.5,0.0,0.0,minigames
        322,4,-59: 322.5,4,-58.5,0.0,0.0,minigames
        308,4,-64: 308.5,4,-63.5,0.0,0.0,minigames
        307,4,-64: 307.5,4,-63.5,0.0,0.0,minigames
        307,4,-65: 307.5,4,-64.5,0.0,0.0,minigames
        313,4,-50: 313.5,4,-49.5,0.0,0.0,minigames
        311,4,-35: 311.5,4,-34.5,0.0,0.0,minigames
      containers:
        309,5,-33: 309,5,-33,0.0,0.0,minigames
        323,4,-64: 323,4,-64,0.0,0.0,minigames
      l1: 287,8,-81,0.0,0.0,minigames
      l2: 324,16,-69,0.0,0.0,minigames
      p1: 267,3,-85,0.0,0.0,minigames
      p2: 337,42,-16,0.0,0.0,minigames
      lobby: 318.5,9,-78.5,255.05,0.0,minigames
      spectator: 298.5,9,-72.5,279.6,0.0,minigames
      exit: 350.5,4,-39.5,111.0,0.0,minigames
      arena: 298.5,4,-36.5,83.93,0.0,minigames
    class-limits:
      Archer: -1
      Oddjob: -1
      Chemist: -1
      Tank: -1
      Knight: -1
