  nopermission: '&4You do not have permission to execute this command!'
  notonline: '&6&l%player &cis not online!'
  flytimer-args: '&cUsage: /flytimer <Player> <Time + s|m|h>'
  timespecify: '&cTo specify a time, give a number followed by s|m|h, for example( /flytimer CoolGamerXD 5s )'
  flytimer-get: '&a&l[FlyTimer] &eYou have fly mode for &b&l%time !'
  flytimer-give: '&a&l[FlyTimer] &eYou gave &6&l%player &efly mode for &b%time'
  flytimer-timerup: '&a&l[FlyTimer] &cYour flying period is over!'
  gmtimer-args: '&cUsage: /gmtimer <Player> <Time + s|m|h>'
  gmtimer-timespecify: '&cTo specify a time, give a number followed by s|m|h, for example( /gmtimer CoolGamerXD 5s )'
  gmtimer-get: '&a&l[GamemodeTimer] &eYou have creative mode for &b&l%time !'
  gmtimer-give: '&a&l[GamemodeTimer] &eYou gave &6&l%player &ecreative mode for &b%time'
  gmtimer-timerup: '&a&l[GamemodeTimer] &cYour gamemode has been reset to survival!'